# Generated by Django 3.0.7 on 2020-09-28 10:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_auto_20200913_1053'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentprofile',
            name='parent',
        ),
        migrations.RemoveField(
            model_name='studentprofile',
            name='user',
        ),
        migrations.DeleteModel(
            name='Student',
        ),
        migrations.DeleteModel(
            name='StudentProfile',
        ),
    ]
