# Generated by Django 3.1 on 2020-10-17 04:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SiteConfig',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=50, verbose_name='Key')),
                ('valye', models.CharField(max_length=50, verbose_name='Value')),
            ],
            options={
                'verbose_name': 'SiteConfig',
                'verbose_name_plural': 'SiteConfigs',
            },
        ),
    ]
