# Generated by Django 3.1 on 2020-10-17 04:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='siteconfig',
            old_name='valye',
            new_name='value',
        ),
    ]
