# Generated by Django 3.1 on 2020-10-18 03:46

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_auto_20201017_0908'),
    ]

    operations = [
        migrations.CreateModel(
            name='CheckoutData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contact', models.CharField(max_length=13, validators=[django.core.validators.RegexValidator(message="Entered mobile number isn't in a right format!", regex='^[0-9]{9,15}$')])),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.order', verbose_name='Order')),
            ],
            options={
                'verbose_name': 'CheckoutData',
                'verbose_name_plural': 'CheckoutData',
            },
        ),
    ]
