# Generated by Django 3.1 on 2020-10-18 03:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_checkoutdata'),
    ]

    operations = [
        migrations.AddField(
            model_name='checkoutdata',
            name='message',
            field=models.CharField(default='a', max_length=500, verbose_name='Message'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='checkoutdata',
            name='remarks',
            field=models.CharField(default='a', max_length=200, verbose_name='Remarks'),
            preserve_default=False,
        ),
    ]
