# Generated by Django 3.1 on 2020-10-18 03:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_auto_20201018_0347'),
    ]

    operations = [
        migrations.AlterField(
            model_name='checkoutdata',
            name='message',
            field=models.TextField(verbose_name='Message'),
        ),
        migrations.AlterField(
            model_name='checkoutdata',
            name='remarks',
            field=models.TextField(verbose_name='Remarks'),
        ),
    ]
