# Generated by Django 3.1 on 2020-10-18 08:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_auto_20201018_0359'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='order',
            options={'ordering': ['-ordered_date'], 'verbose_name': 'Order', 'verbose_name_plural': 'Orders'},
        ),
        migrations.AlterField(
            model_name='checkoutdata',
            name='order',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='main.order', verbose_name='Order'),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('NO', 'Not-Ordered'), ('O', 'Ordered'), ('CO', 'Confirmed'), ('S', 'Fulfilled'), ('CA', 'Cancelled')], default='NO', max_length=20),
        ),
    ]
