# Generated by Django 3.1 on 2020-10-28 02:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_auto_20201018_1025'),
    ]

    operations = [
        migrations.CreateModel(
            name='Carousel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('carousel_name', models.CharField(max_length=50)),
            ],
        ),
        migrations.AlterModelOptions(
            name='siteconfig',
            options={'verbose_name': 'Site Config', 'verbose_name_plural': 'Site Configs'},
        ),
        migrations.CreateModel(
            name='CarouselPhoto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='carousel_image')),
                ('carousel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.carousel')),
            ],
        ),
    ]
