# Generated by Django 3.1 on 2020-10-30 05:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_auto_20201028_0259'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='carouselphoto',
            name='carousel',
        ),
        migrations.DeleteModel(
            name='Carousel',
        ),
        migrations.DeleteModel(
            name='CarouselPhoto',
        ),
    ]
