# Generated by Django 3.0.7 on 2020-09-28 10:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, unique=True)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventory.Category')),
            ],
            options={
                'verbose_name_plural': 'Categories',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=240, unique=True)),
                ('description', models.TextField(verbose_name='')),
                ('image', models.ImageField(blank=True, null=True, upload_to='item_images', verbose_name='')),
                ('cost_price', models.IntegerField(verbose_name='')),
                ('quantity', models.IntegerField(verbose_name='')),
                ('selling_price', models.IntegerField(verbose_name='')),
                ('about_seller', models.TextField(verbose_name='')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.Category', verbose_name='category')),
            ],
        ),
    ]
