# Generated by Django 3.0.7 on 2020-09-29 06:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_item_brand'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='about_seller',
            field=models.TextField(verbose_name='About Seller'),
        ),
        migrations.AlterField(
            model_name='item',
            name='brand',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Product Brand'),
        ),
        migrations.AlterField(
            model_name='item',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='categories', to='inventory.Category', verbose_name='category'),
        ),
        migrations.AlterField(
            model_name='item',
            name='cost_price',
            field=models.IntegerField(verbose_name='Cost Price'),
        ),
        migrations.AlterField(
            model_name='item',
            name='description',
            field=models.TextField(verbose_name='Product Description'),
        ),
        migrations.AlterField(
            model_name='item',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='item_images', verbose_name='Product Image'),
        ),
        migrations.AlterField(
            model_name='item',
            name='name',
            field=models.CharField(max_length=240, unique=True, verbose_name='Product Name'),
        ),
        migrations.AlterField(
            model_name='item',
            name='quantity',
            field=models.IntegerField(verbose_name='Available Quantity'),
        ),
        migrations.AlterField(
            model_name='item',
            name='selling_price',
            field=models.IntegerField(verbose_name='Selling Price'),
        ),
    ]
