# Generated by Django 3.0.7 on 2020-10-01 05:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0004_auto_20201001_0511'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='cost_price',
            field=models.IntegerField(default=0, verbose_name='Cost Price'),
        ),
        migrations.AlterField(
            model_name='item',
            name='selling_price',
            field=models.IntegerField(default=0, verbose_name='Selling Price'),
        ),
    ]
