# Generated by Django 3.0.7 on 2020-10-01 05:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0005_auto_20201001_0512'),
    ]

    operations = [
        migrations.CreateModel(
            name='DebitTransaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_seller', models.CharField(max_length=128, verbose_name='Seller Name')),
                ('cost', models.IntegerField(verbose_name='Cost Price Per Quantity Unit')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.Item', verbose_name='Inventory Item')),
            ],
        ),
    ]
