# Generated by Django 3.0.7 on 2020-10-01 05:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0007_auto_20201001_0529'),
    ]

    operations = [
        migrations.AddField(
            model_name='debittransaction',
            name='sp',
            field=models.IntegerField(default=0, verbose_name='Selling Price'),
        ),
    ]
