# Generated by Django 3.0.7 on 2020-10-01 06:03

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0008_debittransaction_sp'),
    ]

    operations = [
        migrations.RenameField(
            model_name='debittransaction',
            old_name='from_seller',
            new_name='seller',
        ),
        migrations.AddField(
            model_name='debittransaction',
            name='date',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2020, 10, 1, 6, 3, 39, 56420, tzinfo=utc), verbose_name='Date Bought'),
            preserve_default=False,
        ),
    ]
