# Generated by Django 3.0.7 on 2020-10-01 06:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0009_auto_20201001_0603'),
    ]

    operations = [
        migrations.AddField(
            model_name='debittransaction',
            name='paid',
            field=models.IntegerField(default=0, verbose_name='Paid Amount'),
        ),
    ]
