# Generated by Django 3.0.7 on 2020-10-01 15:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0010_debittransaction_paid'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='debittransaction',
            options={'ordering': ['-date']},
        ),
        migrations.AlterModelOptions(
            name='item',
            options={'ordering': ['name']},
        ),
        migrations.AlterField(
            model_name='debittransaction',
            name='seller',
            field=models.CharField(max_length=128, verbose_name='Seller Name or Company'),
        ),
        migrations.CreateModel(
            name='CreditTransaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('buyer', models.CharField(max_length=128, verbose_name='Buyer Name or Company')),
                ('paid', models.IntegerField(default=0, verbose_name='Paid Amount')),
                ('sp', models.IntegerField(default=0, verbose_name='Selling Price')),
                ('quantity', models.IntegerField(default=0, verbose_name='Quantity')),
                ('discount', models.FloatField(verbose_name='Discount Percentage')),
                ('remarks', models.TextField(blank=True, null=True, verbose_name='Remarks on Deal')),
                ('date', models.DateTimeField(auto_now_add=True, verbose_name='Date Sold')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.Item', verbose_name='Inventory Item')),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
    ]
