# Generated by Django 3.0.7 on 2020-10-01 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0011_auto_20201001_1503'),
    ]

    operations = [
        migrations.AlterField(
            model_name='credittransaction',
            name='discount',
            field=models.FloatField(default=0, verbose_name='Discount Percentage'),
        ),
    ]
