# Generated by Django 3.0.7 on 2020-10-02 06:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0013_remove_credittransaction_sp'),
    ]

    operations = [
        migrations.CreateModel(
            name='CreditTransactionInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('buyer', models.CharField(max_length=128, verbose_name='Buyer Name or Company')),
                ('discount', models.FloatField(default=0, verbose_name='Discount Percentage')),
            ],
            options={
                'ordering': ['-transaction__date'],
            },
        ),
        migrations.CreateModel(
            name='DebitTransactionInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seller', models.CharField(max_length=128, verbose_name='Seller Name or Company')),
                ('cost', models.IntegerField(verbose_name='Cost Price Per Quantity Unit')),
                ('paid', models.IntegerField(default=0, verbose_name='Paid Amount')),
                ('sp', models.IntegerField(default=0, verbose_name='Selling Price per Quantity Unit')),
            ],
            options={
                'ordering': ['-transaction__date'],
            },
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('_type', models.CharField(choices=[('STOCK OUT', 'Stock Out'), ('STOCK IN', 'Stock In')], default='STOCK IN', max_length=50, verbose_name='Type')),
                ('paid', models.IntegerField(default=0, verbose_name='Paid Amount')),
                ('quantity', models.IntegerField(default=0, verbose_name='Quantity')),
                ('remarks', models.TextField(blank=True, null=True, verbose_name='Remarks on Deal')),
                ('date', models.DateTimeField(auto_now_add=True, verbose_name='Date of Transaction')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.Item', verbose_name='Inventory Item')),
            ],
        ),
        migrations.RemoveField(
            model_name='debittransaction',
            name='item',
        ),
        migrations.DeleteModel(
            name='CreditTransaction',
        ),
        migrations.DeleteModel(
            name='DebitTransaction',
        ),
        migrations.AddField(
            model_name='debittransactioninfo',
            name='transaction',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='inventory.Transaction', verbose_name='info'),
        ),
        migrations.AddField(
            model_name='credittransactioninfo',
            name='transaction',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='inventory.Transaction', verbose_name='info'),
        ),
        migrations.CreateModel(
            name='CreditTransaction',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('inventory.transaction',),
        ),
        migrations.CreateModel(
            name='DebitTransaction',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('inventory.transaction',),
        ),
    ]
