# Generated by Django 3.1 on 2020-10-02 15:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0015_remove_debittransactioninfo_paid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='debittransactioninfo',
            name='sp',
        ),
        migrations.AlterField(
            model_name='credittransactioninfo',
            name='transaction',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='creditInfo', to='inventory.credittransaction', verbose_name='info'),
        ),
        migrations.AlterField(
            model_name='debittransactioninfo',
            name='transaction',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='debitInfo', to='inventory.debittransaction', verbose_name='info'),
        ),
        migrations.AlterField(
            model_name='item',
            name='cost_price',
            field=models.IntegerField(default=0, verbose_name='Latest Cost Price'),
        ),
        migrations.AlterField(
            model_name='item',
            name='selling_price',
            field=models.IntegerField(default=0, verbose_name='Current Selling Price'),
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField(verbose_name='Amount To add in Transaction')),
                ('date', models.DateField(auto_now_add=True, verbose_name='Date of Payment')),
                ('transaction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.transaction', verbose_name='Payment For Transaction')),
            ],
        ),
    ]
