# Generated by Django 3.1 on 2020-10-03 03:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0016_auto_20201002_1505'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='debittransactioninfo',
            name='transaction',
        ),
        migrations.AddField(
            model_name='transaction',
            name='cost',
            field=models.IntegerField(default=0, verbose_name='Cost Price Per Quantity Unit'),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='CreditTransactionInfo',
        ),
        migrations.DeleteModel(
            name='DebitTransactionInfo',
        ),
    ]
