# Generated by Django 3.1 on 2020-10-03 03:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0018_auto_20201003_0324'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='balanced',
            field=models.BooleanField(default=False, editable=False, verbose_name='Balanced'),
            preserve_default=False,
        ),
    ]
