# Generated by Django 3.1 on 2020-10-03 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0019_transaction_balanced'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='cost_price',
            field=models.FloatField(default=0, verbose_name='Latest Cost Price'),
        ),
        migrations.AlterField(
            model_name='item',
            name='selling_price',
            field=models.FloatField(default=0, verbose_name='Current Selling Price'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='amount',
            field=models.FloatField(verbose_name='Amount To add in Transaction'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='cost',
            field=models.FloatField(default=0, verbose_name='Cost Price Per Quantity Unit'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='paid',
            field=models.FloatField(default=0, verbose_name='Paid Amount'),
        ),
    ]
