# Generated by Django 3.1 on 2020-10-03 09:48

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0021_auto_20201003_0947'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='contact',
            field=models.CharField(max_length=13, validators=[django.core.validators.RegexValidator(message="Entered mobile number isn't in a right format!", regex='^[0-9]{10,15}$')]),
        ),
    ]
