# Generated by Django 3.1 on 2020-10-09 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0024_auto_20201009_0538'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='base_payment',
            field=models.BooleanField(default=False, editable=False, verbose_name='Is Base Payment'),
        ),
    ]
