# Generated by Django 3.1 on 2020-10-09 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0025_payment_base_payment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='base_payment',
            field=models.BooleanField(default=False, verbose_name='Is Base Payment'),
        ),
    ]
