# Generated by Django 3.1 on 2020-10-18 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0026_auto_20201009_1356'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='image',
            field=models.ImageField(default='image-not-available.jpg', upload_to='product_images', verbose_name='Product Image'),
        ),
    ]
