# Generated by Django 3.1 on 2020-10-30 05:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0027_auto_20201018_1047'),
    ]

    operations = [
        migrations.CreateModel(
            name='Carousel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('carousel_name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='CarouselPhoto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='carousel_image')),
                ('carousel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photo_set', to='inventory.carousel')),
            ],
        ),
    ]
