# Generated by Django 3.0.7 on 2020-10-01 05:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0004_auto_20201001_0511'),
        ('invoice', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='invoice',
            options={'ordering': ['-date_created']},
        ),
        migrations.AlterField(
            model_name='invoiceitem',
            name='invoice',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='MainInvoice', to='invoice.Invoice', verbose_name='Invoice'),
        ),
        migrations.AlterField(
            model_name='invoiceitem',
            name='item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.Item', verbose_name='Item Name'),
        ),
        migrations.AlterField(
            model_name='invoiceitem',
            name='sp',
            field=models.IntegerField(verbose_name='Selling Price / Quantity'),
        ),
    ]
